### ISSUE TITLE
Is this extension working in Lens 4?

### ISSUE THREAD

**Issue by weyderfs** [nevalla/lens-resource-map-extension#10]
Hello everyone,
I have followed the steps of installation to Lens 4, but now found the extension working intro de IDE (maybe I'm does some miss configuration).  My Lens at in the version `4.2.5`.

I'd tried reload, close and the Lens, but still missing, tried the `latest`version and `0.2.0`like the tutorial explains. More someone with this trouble?

**Comment by nevalla** [comment]
`0.2.0` should be compatible with Lens 4.2.5. You should see Resource Map menu item on cluster menu. If you install the extension do you see it as enabled on extensions list?

**Comment by weyderfs** [comment]
> `0.2.0` should be compatible with Lens 4.2.5. You should see Resource Map menu item on cluster menu. If you install the extension do you see it as enabled on extensions list?

I'd upgraded to Lens 5 and works.
