### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by fabriziofiorucci** [nevalla/lens-resource-map-extension#12]
Hello,

I installed the resource map on Lens 5.2.2 running as an AppImage from Linux (Lens-5.2.2-latest.20210917.1.x86_64.AppImage) and I'm getting this crash report:
 
![Untitled](https://user-images.githubusercontent.com/58330741/133854580-6e590eac-d666-4ac0-869f-4750f83c79f0.png)

This messes up the whole lens gui and the only way to get it back to normal is by removing the resource map. Any idea on why this is happening?

Thanks

**Comment by IsaacLeeWebDev** [comment]
Same here, same version, on macOS. Just downloaded the latest version of the Lens .dmg today.

**Comment by artyom-p** [comment]
Same for me, Windows 10

**Comment by nevalla** [comment]
Fixed in #13

**Comment by fabriziofiorucci** [comment]
Thanks!
