### ISSUE TITLE
version 1.1.0 not showing up in Lens GUI windows 11

### ISSUE THREAD

**Issue by ihsanmv** [nevalla/lens-resource-map-extension#28]
Installed version 1.1.0 in windows 
<img width="724" alt="image" src="https://github.com/nevalla/lens-resource-map-extension/assets/29991333/773686e6-e609-46cc-88d9-90188e90dbcf">

but not showing anything in the GUI
<img width="213" alt="image" src="https://github.com/nevalla/lens-resource-map-extension/assets/29991333/716e6e4a-3bf7-444b-ae58-173fd684a92d">

extension files already present in .k8slens\extensions\nevalla--kube-resource-map

since its windows I tried couple reboot but still I have the issue 

following is the lens version I am using 

<img width="220" alt="image" src="https://github.com/nevalla/lens-resource-map-extension/assets/29991333/6fd80b59-289f-45a0-8cea-ef95e439dc22">

**Comment by git-volk** [comment]
Open Developer Console (View -> Toggle Developer Tools)
I see error like _"can't find file for render /home/user/.config/Lens/node_modules/@nevalla/kube-resource-map/dist/renderer.js"_

Just create this path by copy file from _"/home/user/.k8slens/extensions/nevalla--kube-resource-map"_

Reload Lens and it works!!!
![image](https://github.com/user-attachments/assets/8905c654-8045-405c-b475-bc00efcdfbc6)

**Comment by ihsanmv** [comment]
@git-volk Thanks for sharing this I can see Resource Map as expected. I had to create the path as C:\Users\user\AppData\Roaming\Lens\node_modules\@nevalla\kube-resource-map\dist\ and copied the file from \home\user\.k8slens\extensions\nevalla--kube-resource-map

<img width="399" alt="2024-10-31" src="https://github.com/user-attachments/assets/551cf0ce-5338-4ab3-8738-e1d7cd2e68be">
