### ISSUE TITLE
Support navigation from graph node in map to detailed view of resource

### ISSUE THREAD

**Issue by plevart** [nevalla/lens-resource-map-extension#4]
Hi,
This is a very nice Lens plugin. It would benefit greatly if there was a way to navigate from the graph nodes to the various detail panels for the k8s resources that graph nodes represent (i.e. the same detail panels that slide from right when you select a particular resource in the Lens browser). I don't know if Lens plugin API allows to do that easily though. But if it doesn't maybe it could get extended?

**Comment by nevalla** [comment]
Yes, agree this would be super cool feature. I'll try to find some time for this.
